name: Build and Publish
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x MindustryPlugin/gradlew
    - name: Build with Gradle
      run: cd MindustryPlugin && ./gradlew shadowJar
    - name: Publish artifacts
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_PATH: MindustryPlugin/build/libs/
        GITHUB_TOKEN: ${{github.token}}
